### ISSUE TITLE
City file url is deprecated

### ISSUE THREAD

**Issue by MichaelRSilva** [flaviostutz/ruller#9]
In the `Dockerfile` the cities file is downloaded `https://raw.githubusercontent.com/chandez/Estados-Cidades-IBGE/master/Municipios.sql`, but this url is deprecated, the new url is: `https://raw.githubusercontent.com/chandez/Estados-Cidades-IBGE/master/sql/Municipios.sql`. How about we pass this url via ARG ? Like for example:

```
FROM golang:1.14.3-alpine3.11 AS BUILD

ARG BRAZIL_CITIES_PATH

...

RUN curl $BRAZIL_CITIES_PATH --output Municipios.sql

...

```

In docker-compose it would look something like this:

```
...

ruller-sample:
    build:
      context: .
      args:
        MAXMIND_LICENSE_KEY: ""
        BRAZIL_CITIES_PATH: "https://raw.githubusercontent.com/chandez/Estados-Cidades-IBGE/master/sql/Municipios.sql"
...

```
